#ifndef VARIABLES_GLOBALES_H_
#define VARIABLES_GLOBALES_H_

typedef enum {
    HANDSHAKE_CPU = 1,
    HANDSHAKE_IO  = 2,
    HANDSHAKE_KERNEL_SCHEDULER = 3,
    HANDSHAKE_MEMORY_STICK = 4,
    HANDSHAKE_SWAP = 5,

    OP_CREAR_PROCESO = 10,
    OP_FIN_PROCESO = 11,
    OP_SYSCALL     = 12,
    OP_INTERRUPCION= 13,

    OP_IO_FIN      = 20,

    OP_EJECUTAR_PROCESO = 30,
    // CODIGOS DEL SCHEDULER
    INGRESO_CPU = 100,
    INGRESO_IO,
	A_LA_ESPERA_IO,
	SOLICITUD_IO_SLEEP,
	REGRESO_IO_SLEEP,
	SOLICITUD_IO_STDIN,
	REGRESO_IO_STDIN,
	SOLICITUD_IO_STDOUT,
	REGRESO_IO_STDOUT

} codigo_operacion;

#endif